'use client'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { Users, Plus, Search, RefreshCw, Edit2, Trash2, ChevronLeft, ChevronRight } from 'lucide-react'
import { useAuthStore } from '../../store/useAuthStore'
import { clientListKey, useClientStore } from '../../store/useClientStore'
import { useDebounce } from '../../utils/useDebounce'
import { deleteClient } from '../../api/clients'
import { toast } from '../../utils/toast'
import type { Client, ClientStats, ClientQueryParams, ClientsListResponse } from '../../types/client'
import { Breadcrumb } from '../ui/Breadcrumb'
import { ClientError, ClientLoading, ClientConfirm, buttonClass } from './ClientModal'
import { ClientFormModal } from './ClientFormModal'
import { ClientDetailModal } from './ClientDetailModal'

export function ClientsView() {
  const params = useSearchParams()
  const linkedId = params.get('clientId'), linkedTab = params.get('tab') || 'overview'
  return <ClientsDirectory key={`${linkedId}:${linkedTab}`} linkedId={linkedId} linkedTab={linkedTab} />
}

function ClientsDirectory({ linkedId, linkedTab }: { linkedId: string | null; linkedTab: string }) {
  const userId = useAuthStore(state => state.user?.id)
  const [search, setSearch] = useState(''), [page, setPage] = useState(1), [status, setStatus] = useState<'ALL' | 'ACTIVE' | 'INACTIVE'>('ALL'), [scope, setScope] = useState<'ALL' | 'MINE'>('ALL')
  const [form, setForm] = useState<{ client?: Client } | null>(null), [detailId, setDetailId] = useState<string | null>(linkedId), [deleting, setDeleting] = useState<Client | null>(null)
  const debounced = useDebounce(search, 300)
  const query = useMemo<ClientQueryParams>(() => ({ page, limit: 15, search: debounced, status, scope }), [page, debounced, status, scope]), key = clientListKey(query)
  const data = useClientStore(state => state.cache[key]?.data as ClientsListResponse | undefined), loading = useClientStore(state => state.loading[key]), error = useClientStore(state => state.errors[key]), stats = useClientStore(state => state.cache.stats?.data as ClientStats | undefined), statsError = useClientStore(state => state.errors.stats)
  const loadList = useClientStore(state => state.loadList), loadStats = useClientStore(state => state.loadStats), version = useClientStore(state => state.listVersion)
  useEffect(() => {
    let current = true
    if (userId) void loadList(query).then(result => { if (current && query.page! > result.pagination.totalPages) setPage(result.pagination.totalPages) }).catch(() => {})
    return () => { current = false }
  }, [loadList, query, version, userId])
  useEffect(() => { if (userId) void loadStats().catch(() => {}) }, [loadStats, version, userId])
  const refresh = () => { void loadList(query, true).catch(() => {}); void loadStats(true).catch(() => {}) }
  const actions = (client: Client) => <div className="flex gap-1"><button aria-label={`Edit ${client.name}`} onClick={() => setForm({ client })} className="p-3 text-muted-text hover:text-gold"><Edit2 className="h-4 w-4" /></button><button aria-label={`Delete ${client.name}`} onClick={() => setDeleting(client)} className="p-3 text-muted-text hover:text-red-500"><Trash2 className="h-4 w-4" /></button></div>
  return <><Breadcrumb items={[{ label: 'Home', href: '/dashboard' }, { label: 'Clients' }]} /><div className="my-5 flex items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-black uppercase tracking-tight"><Users className="h-5 w-5 text-gold" />Client directory</h1><p className="mt-1 text-xs text-muted-text">Clients, partner assignments, property shortlists and sharing.</p></div><button onClick={() => setForm({})} className={`${buttonClass} shrink-0 bg-gold text-background`}><Plus className="h-4 w-4" />Add client</button></div>
    <div className="mb-5 grid grid-cols-2 gap-px border border-border bg-border sm:grid-cols-4">{[['Total clients', stats?.totalClients], ['Active', stats?.activeClients], ['Inactive', stats?.inactiveClients], ['My clients', stats?.myClientsCount]].map(([label, value]) => <div key={label} className="bg-surface px-4 py-4"><p className="text-[9px] font-bold uppercase tracking-wider text-muted-text">{label}</p><p className="mt-2 text-2xl font-black tabular-nums">{value ?? '—'}</p></div>)}</div>
    <ClientError message={statsError} retry={() => void loadStats(true).catch(() => {})} />
    <div className="mb-4 border border-border bg-surface"><div className="flex border-b border-border"><div className="relative min-w-0 flex-1"><Search className="absolute left-3.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-text" /><input aria-label="Search clients" value={search} onChange={event => { setSearch(event.target.value); setPage(1) }} placeholder="Search name, phone or email..." className="w-full bg-transparent py-3 pl-10 pr-3 text-xs outline-none" /></div><button onClick={refresh} className="flex items-center gap-2 border-l border-border px-3 text-[10px] font-bold uppercase text-muted-text"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} /><span className="hidden sm:inline">Refresh</span></button></div><div className="flex gap-1 overflow-x-auto p-2">{(['ALL', 'MINE'] as const).map(value => <button key={value} aria-pressed={scope === value} onClick={() => { setScope(value); setPage(1) }} className={`min-h-9 shrink-0 px-3 text-[10px] font-bold uppercase ${scope === value ? 'bg-foreground text-background' : 'text-muted-text'}`}>{value === 'ALL' ? 'All clients' : 'My clients'}</button>)}<span className="mx-1 w-px shrink-0 bg-border" />{(['ALL', 'ACTIVE', 'INACTIVE'] as const).map(value => <button key={value} aria-pressed={status === value} onClick={() => { setStatus(value); setPage(1) }} className={`min-h-9 shrink-0 px-3 text-[10px] font-bold uppercase ${status === value ? 'bg-foreground text-background' : 'text-muted-text'}`}>{value === 'ALL' ? 'All statuses' : value}</button>)}</div></div>
    <ClientError message={error} retry={() => void loadList(query, true).catch(() => {})} />
    <div className="overflow-hidden border border-border bg-surface">{!data && !error ? <ClientLoading text="Loading clients..." /> : !data?.clients.length ? <div className="p-12 text-center"><Users className="mx-auto mb-3 h-7 w-7 text-gold" /><h3 className="text-sm font-bold uppercase">No clients found</h3><p className="mt-2 text-xs text-muted-text">Add a client or adjust your search and filters.</p></div> : <>
      <div className="divide-y divide-border sm:hidden">{data.clients.map(client => <article key={client.id} className="p-4"><button onClick={() => setDetailId(client.id)} className="block w-full text-left"><div className="flex justify-between gap-3"><p className="break-words text-xs font-bold">{client.name}</p><span className="text-[9px] font-bold uppercase text-muted-text">{client.status}</span></div><p className="mt-2 text-xs">{client.phone}</p><p className="mt-1 break-words text-[10px] text-muted-text">{client.assignedPartners.map(item => item.partner.name || item.partner.email).join(', ') || 'Unassigned'}</p></button><div className="mt-2 flex items-center justify-between"><button onClick={() => setDetailId(client.id)} className="text-[10px] font-bold uppercase text-gold">{client._count?.shortlistedProperties || 0} shortlisted · View client</button>{actions(client)}</div></article>)}</div>
      <div className="hidden overflow-x-auto sm:block"><table className="w-full text-left"><thead className="border-b border-border bg-surface-secondary"><tr>{['Client', 'Contact', 'Assigned partners', 'Shortlisted', 'Status', 'Actions'].map(title => <th key={title} className="px-4 py-3 text-[9px] font-bold uppercase tracking-wider text-muted-text">{title}</th>)}</tr></thead><tbody className="divide-y divide-border">{data.clients.map(client => <tr key={client.id} tabIndex={0} aria-label={`View client ${client.name}`} onClick={event => { if (!(event.target as HTMLElement).closest('a,button')) setDetailId(client.id) }} onKeyDown={event => { if (event.target === event.currentTarget && ['Enter', ' '].includes(event.key)) { event.preventDefault(); setDetailId(client.id) } }} className="group cursor-pointer transition-colors hover:bg-surface-secondary focus-visible:outline-2 focus-visible:outline-gold"><td className="px-4 py-3.5"><button onClick={() => setDetailId(client.id)} className="text-xs font-bold group-hover:text-gold">{client.name}</button><p className="mt-1 max-w-60 truncate text-[10px] text-muted-text">{client.address || 'No address recorded'}</p></td><td className="px-4 py-3.5 text-xs"><a href={`tel:${client.phone}`} className="hover:text-gold">{client.phone}</a><p className="mt-1 text-[10px] text-muted-text">{client.email || '—'}</p></td><td className="max-w-64 px-4 py-3.5 text-xs">{client.assignedPartners.map(item => item.partner.name || item.partner.email).join(', ') || 'Unassigned'}</td><td className="px-4 py-3.5 text-xs font-bold text-gold">{client._count?.shortlistedProperties || 0}</td><td className="px-4 py-3.5"><span className="inline-flex items-center gap-1.5 text-[10px] font-bold uppercase"><span className={`h-1.5 w-1.5 ${client.status === 'ACTIVE' ? 'bg-foreground' : 'bg-muted-text'}`} />{client.status}</span></td><td className="px-2 py-2">{actions(client)}</td></tr>)}</tbody></table></div>
    </>}{data && <div className="flex items-center justify-between border-t border-border bg-surface-secondary px-4 py-3 text-[10px] text-muted-text"><span>{data.pagination.total} clients</span><div className="flex items-center gap-3"><button aria-label="Previous page" disabled={page === 1 || loading} onClick={() => setPage(page - 1)} className="border border-border p-2.5 disabled:opacity-30"><ChevronLeft className="h-3 w-3" /></button>{page} / {data.pagination.totalPages}<button aria-label="Next page" disabled={!data.pagination.hasNextPage || loading} onClick={() => setPage(page + 1)} className="border border-border p-2.5 disabled:opacity-30"><ChevronRight className="h-3 w-3" /></button></div></div>}</div>
    {detailId && <ClientDetailModal key={`${detailId}:${linkedTab}`} clientId={detailId} initialTab={linkedTab} onClose={() => setDetailId(null)} />}
    {form && <ClientFormModal client={form.client} onClose={() => setForm(null)} onSaved={() => {}} />}
    {deleting && <ClientConfirm title={`Delete ${deleting.name}?`} description="The property inventory will be kept. Clients with documents or sharing history must be marked Inactive instead." onClose={() => setDeleting(null)} action={async () => { await deleteClient(deleting.id); useClientStore.getState().removedClient(deleting.id); if (detailId === deleting.id) setDetailId(null); toast.success('Client deleted') }} />}
  </>
}
