'use client'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { Building2, Plus, Share2, Edit2, Trash2, Copy, ExternalLink, Check, RefreshCw } from 'lucide-react'
import { useClientStore } from '../../store/useClientStore'
import { removeClientShortlist, revokeClientShare, updateClientShare } from '../../api/clients'
import { propertyComposerUrl } from '../../templates/client-property-message'
import { getApiErrorMessage } from '../../utils/errorHandler'
import { toast } from '../../utils/toast'
import type { ClientDetail, ClientShortlistedProperty, ClientPropertyShare } from '../../types/client'
import { ClientModal, ClientError, ClientLoading, ClientConfirm, buttonClass, labelClass } from './ClientModal'
import { ClientFormModal } from './ClientFormModal'
import { ClientShortlistModal, ClientShortlistEditModal } from './ClientShortlistModal'
import { ClientShareModal } from './ClientShareModal'
import { ClientDocuments } from './ClientDocuments'

export function ClientDetailModal({ clientId, onClose, initialTab = 'overview' }: { clientId: string; onClose: () => void; initialTab?: string }) {
  const key = `detail:${clientId}`
  const client = useClientStore(state => state.cache[key]?.data as ClientDetail | undefined), loading = useClientStore(state => state.loading[key]), error = useClientStore(state => state.errors[key]), load = useClientStore(state => state.loadDetail)
  const [tab, setTab] = useState(initialTab), [edit, setEdit] = useState(false), [add, setAdd] = useState(false), [feedback, setFeedback] = useState<ClientShortlistedProperty | null>(null), [sharing, setSharing] = useState<ClientShortlistedProperty | null>(null), [remove, setRemove] = useState<ClientShortlistedProperty | null>(null), [revoke, setRevoke] = useState<ClientPropertyShare | null>(null), [busyShare, setBusyShare] = useState<string | null>(null)
  useEffect(() => { void load(clientId).catch(() => {}) }, [load, clientId])
  const recordStatus = async (share: ClientPropertyShare, status: 'COMPOSER_OPENED' | 'SENT_CONFIRMED') => {
    setBusyShare(share.id)
    try { const updated = await updateClientShare(clientId, share.id, status); useClientStore.getState().shareChanged(clientId, updated) }
    catch (error) { toast.error('Unable to update sharing history', getApiErrorMessage(error)) } finally { setBusyShare(null) }
  }
  const copy = async (share: ClientPropertyShare) => {
    try { await navigator.clipboard.writeText(share.publicUrl); toast.success('Property link copied') }
    catch { toast.error('Unable to copy', 'Open the link and copy it from the address bar.') }
  }
  return <><ClientModal title={client?.name || 'Client details'} onClose={onClose} footer={<><button onClick={onClose} className={buttonClass}>Close</button>{client && <button onClick={() => setEdit(true)} className={`${buttonClass} bg-gold text-background`}><Edit2 className="h-3.5 w-3.5" />Edit client</button>}</>}>
    <ClientError message={error} retry={() => void load(clientId, true).catch(() => {})} />
    {!client ? <ClientLoading text="Loading client details..." /> : <>
      <div className="mb-5 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-1.5 text-[10px] font-bold uppercase"><span className={`h-1.5 w-1.5 ${client.status === 'ACTIVE' ? 'bg-foreground' : 'bg-muted-text'}`} />{client.status}</span><button aria-label="Refresh client details" onClick={() => void load(clientId, true).catch(() => {})} className="p-2 text-muted-text hover:text-gold"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button></div>
      <nav aria-label="Client detail tabs" className="mb-5 flex gap-1 overflow-x-auto border-b border-border pb-2">{[['overview', 'Overview'], ['shortlist', `Shortlist (${client.shortlistedProperties.length})`], ['documents', `Documents (${client.documents.length})`], ['history', `Sharing (${client.shares.length})`]].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)} className={`${buttonClass} shrink-0 ${tab === value ? 'border-gold text-gold' : 'text-muted-text'}`}>{label}</button>)}</nav>
      {tab === 'overview' && <div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2">{[['Phone', client.phone], ['Email', client.email], ['WhatsApp', client.whatsappNumber || client.phone], ['Address', client.address], ['Assigned partners', client.assignedPartners.map(item => item.partner.name || item.partner.email).join(', ') || 'Unassigned'], ['Created by', client.createdBy?.name || client.createdBy?.email || 'Partner']].map(([label, value]) => <div key={label}><p className={labelClass}>{label}</p><p className="break-words whitespace-pre-wrap text-xs">{label === 'Phone' ? <a href={`tel:${value}`} className="hover:text-gold">{value}</a> : label === 'Email' && value ? <a href={`mailto:${value}`} className="hover:text-gold">{value}</a> : value || '—'}</p></div>)}</div><div className="border-t border-border pt-4"><p className={labelClass}>Client notes</p><p className="whitespace-pre-wrap text-xs leading-relaxed">{client.notes || 'No notes recorded yet.'}</p></div><div className="grid grid-cols-2 gap-px border border-border bg-border"><button onClick={() => setTab('shortlist')} className="bg-surface p-4 text-left"><p className={labelClass}>Shortlisted properties</p><p className="text-2xl font-black text-gold">{client.shortlistedProperties.length}</p></button><button onClick={() => setTab('history')} className="bg-surface p-4 text-left"><p className={labelClass}>Property shares</p><p className="text-2xl font-black">{client.shares.length}</p></button></div><button onClick={() => { setTab('shortlist'); setAdd(true) }} className={`${buttonClass} bg-gold text-background`}><Plus className="h-4 w-4" />Shortlist a property</button></div>}
      {tab === 'shortlist' && <div className="space-y-4"><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-text">Track properties selected, shared, visited, and client feedback.</p><button onClick={() => setAdd(true)} className={`${buttonClass} shrink-0 bg-gold text-background`}><Plus className="h-3.5 w-3.5" />Add property</button></div>{!client.shortlistedProperties.length && <div className="border border-border p-10 text-center"><Building2 className="mx-auto mb-3 h-7 w-7 text-gold" /><p className="text-xs text-muted-text">No properties shortlisted yet.</p></div>}<div className="grid gap-4 sm:grid-cols-2">{client.shortlistedProperties.map(item => {
        const photo = item.property.media.find(media => media.category === 'PHOTOGRAPH')
        return <article key={item.id} className="border border-border"><Link href={`/dashboard/properties?propertyId=${item.propertyId}`} className="block"><div className="relative flex aspect-[16/9] items-center justify-center bg-surface-secondary">{photo ? <Image unoptimized src={photo.url} alt={item.property.societyBuildingName} fill sizes="(max-width: 640px) 90vw, 360px" className="object-cover" /> : <Building2 className="h-10 w-10 text-gold" />}<span className="absolute bottom-2 left-2 bg-surface/95 px-2 py-1 text-[9px] font-bold uppercase">{item.status.replaceAll('_', ' ')}</span></div></Link><div className="space-y-2 p-3"><Link href={`/dashboard/properties?propertyId=${item.propertyId}`} className="block text-xs font-bold hover:text-gold">{item.property.societyBuildingName}</Link><p className="text-[10px] text-muted-text">{item.property.locationArea}, {item.property.city}</p><p className="text-sm font-bold text-gold">₹{item.property.askingPrice.toLocaleString('en-IN')}{item.property.pricingType === 'RENT' ? ' / month' : ''}</p><p className="text-[10px] text-muted-text">Added by {item.addedBy?.name || 'Partner'}</p>{item.notes && <p className="whitespace-pre-wrap text-xs leading-relaxed">{item.notes}</p>}<div className="flex flex-wrap gap-2 border-t border-border pt-3"><button disabled={item.property.isArchived || item.property.isDraft} onClick={() => setSharing(item)} className={`${buttonClass} text-gold`}><Share2 className="h-3.5 w-3.5" />Share</button><button onClick={() => setFeedback(item)} className={buttonClass}><Edit2 className="h-3.5 w-3.5" />Feedback</button><button aria-label={`Remove ${item.property.societyBuildingName} from shortlist`} onClick={() => setRemove(item)} className="p-3 text-muted-text hover:text-red-500"><Trash2 className="h-4 w-4" /></button></div></div></article>
      })}</div></div>}
      {tab === 'documents' && <ClientDocuments client={client} />}
      {tab === 'history' && <div className="space-y-4">{!client.shares.length && <p className="border border-border p-8 text-center text-xs text-muted-text">No property shares yet. Choose a shortlisted property to create a link.</p>}{client.shares.map(share => {
        const expired = !!share.revokedAt || (!!share.expiresAt && new Date(share.expiresAt) <= new Date()), composer = propertyComposerUrl(share)
        return <article key={share.id} className="border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-xs font-bold">{share.propertySnapshot.societyBuildingName}</h3><p className="mt-1 text-[10px] text-muted-text">{share.createdBy?.name || 'Partner'} · {share.channel} · {new Date(share.createdAt).toLocaleString('en-IN')}</p></div><span className="text-[9px] font-bold uppercase text-muted-text">{share.revokedAt ? 'Revoked' : expired ? 'Expired' : share.status.replaceAll('_', ' ')}</span></div><p className="mt-2 text-[10px] text-muted-text">{share.selectedMediaSnapshot.length} selected photos/videos{share.expiresAt ? ` · Expires ${new Date(share.expiresAt).toLocaleDateString('en-IN')}` : ''}</p><details className="mt-3"><summary className="cursor-pointer text-[10px] font-bold uppercase text-gold">View message</summary><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-relaxed">{share.message}</p></details><div className="mt-4 flex flex-wrap gap-2"><a href={share.publicUrl} target="_blank" rel="noopener noreferrer" className={buttonClass}><ExternalLink className="h-3.5 w-3.5" />Preview</a>{!expired && <><button onClick={() => void copy(share)} className={buttonClass}><Copy className="h-3.5 w-3.5" />Copy link</button>{composer && <a href={composer} target={share.channel === 'WHATSAPP' ? '_blank' : undefined} rel="noopener noreferrer" onClick={() => void recordStatus(share, 'COMPOSER_OPENED')} className={`${buttonClass} text-gold`}>Open {share.channel === 'WHATSAPP' ? 'WhatsApp' : 'email'}</a>}{share.channel !== 'LINK' && share.status !== 'SENT_CONFIRMED' && <button disabled={busyShare === share.id} onClick={() => void recordStatus(share, 'SENT_CONFIRMED')} className={buttonClass}><Check className="h-3.5 w-3.5" />Mark as sent</button>}<button onClick={() => setRevoke(share)} className={`${buttonClass} text-red-500`}>Revoke link</button></>}</div></article>
      })}</div>}
    </>}
  </ClientModal>
    {edit && client && <ClientFormModal client={client} onClose={() => setEdit(false)} />}
    {add && <ClientShortlistModal clientId={clientId} onClose={() => setAdd(false)} onAdded={() => setTab('shortlist')} />}
    {feedback && <ClientShortlistEditModal clientId={clientId} shortlist={feedback} onClose={() => setFeedback(null)} />}
    {sharing && client && <ClientShareModal client={client} shortlist={sharing} onClose={() => setSharing(null)} />}
    {remove && <ClientConfirm title="Remove shortlisted property?" description="The listing will stay in property inventory. Properties with sharing history are kept for tracking." onClose={() => setRemove(null)} action={async () => { await removeClientShortlist(clientId, remove.id); useClientStore.getState().shortlistChanged(clientId, remove.id); toast.success('Property removed from shortlist') }} />}
    {revoke && <ClientConfirm title="Revoke property link?" description="Anyone opening this link will see that it is unavailable. The sharing history will be kept." onClose={() => setRevoke(null)} action={async () => { await revokeClientShare(clientId, revoke.id); useClientStore.getState().shareChanged(clientId, { ...revoke, revokedAt: new Date().toISOString() }); toast.success('Link revoked') }} />}
  </>
}
