'use client'
import { useState } from 'react'
import Image from 'next/image'
import { Building2, MapPin, Phone, Mail, Globe, BedDouble, Bath, Maximize2, ArrowUpRight, ChevronLeft, ChevronRight, Film, Check } from 'lucide-react'
import type { PublicPropertyShare } from '../../types/client'
import { ClientModal, buttonClass } from './ClientModal'

export function DreamKeyPublicFooter({ company }: { company: PublicPropertyShare['company'] }) {
  return <footer className="border-t border-border bg-surface"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 md:grid-cols-2"><div><Image src="/logorm.png" alt={company.name} width={170} height={60} className="mb-4 h-14 w-auto object-contain" /><h2 className="text-lg font-black uppercase tracking-tight">Find your next chapter.</h2><p className="mt-3 max-w-md text-sm leading-relaxed text-muted-text">{company.description}</p><a href={company.website} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-gold">Visit DreamKey <ArrowUpRight className="h-4 w-4" /></a></div><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[0.18em] text-muted-text">Connect with DreamKey</p><div className="space-y-4 text-xs"><a href={`tel:${company.phone.replace(/\s/g, '')}`} className="flex min-h-10 items-center gap-3 hover:text-gold"><Phone className="h-4 w-4 shrink-0 text-gold" />{company.phone}</a><a href={`mailto:${company.email}`} className="flex min-h-10 items-center gap-3 break-all hover:text-gold"><Mail className="h-4 w-4 shrink-0 text-gold" />{company.email}</a><a href={company.website} target="_blank" rel="noopener noreferrer" className="flex min-h-10 items-center gap-3 break-all hover:text-gold"><Globe className="h-4 w-4 shrink-0 text-gold" />{company.website}</a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(company.address)}`} target="_blank" rel="noopener noreferrer" className="flex min-h-10 items-start gap-3 leading-relaxed hover:text-gold"><MapPin className="mt-1 h-4 w-4 shrink-0 text-gold" />{company.address}</a></div></div></div><div className="border-t border-border px-5 py-4 text-center text-[10px] text-muted-text">© {new Date().getFullYear()} {company.name}. Property details and availability are subject to confirmation.</div></footer>
}
export function PublicPropertyPage({ data }: { data: PublicPropertyShare }) {
  const { property, media, company } = data
  const [filter, setFilter] = useState<'ALL' | 'PHOTOGRAPH' | 'VIDEO'>('ALL'), [lightbox, setLightbox] = useState<number | null>(null)
  const hero = media.find(item => item.category === 'PHOTOGRAPH'), gallery = media.filter(item => filter === 'ALL' || item.category === filter)
  const price = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(property.askingPrice)
  const whatsapp = `https://wa.me/${company.whatsappNumber}?text=${encodeURIComponent(`Hi DreamKey, I'm interested in ${property.societyBuildingName} in ${property.locationArea}, ${property.city}. Could you share more details and help arrange a viewing?`)}`
  return <div className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-surface"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4 sm:px-8"><a href={company.website} target="_blank" rel="noopener noreferrer" aria-label="DreamKey website"><Image src="/logorm.png" alt="DreamKey" width={150} height={52} priority className="h-11 w-auto object-contain" /></a><div className="text-right"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-muted-text">A property selected for you</p><a href={`tel:${company.phone.replace(/\s/g, '')}`} className="mt-1 inline-flex min-h-9 items-center gap-2 text-[10px] font-bold text-gold"><Phone className="h-3.5 w-3.5" />{company.phone}</a></div></div></header>
    <main className="mx-auto max-w-7xl px-4 pt-5 pb-12 sm:px-8 sm:pt-8"><div className="mb-4 flex flex-wrap items-center gap-3 text-[9px] font-bold uppercase tracking-[0.18em] text-muted-text"><span className="text-gold">DreamKey collection</span><span className="h-px w-8 bg-border" /><span>{property.propertyType} · For {property.pricingType === 'RENT' ? 'rent' : 'sale'}</span></div>
      <div className="grid gap-0 border border-border bg-surface lg:grid-cols-[1.65fr_1fr]"><div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden bg-surface-secondary sm:aspect-[16/10] lg:aspect-auto lg:min-h-[480px]">{hero ? <><Image unoptimized src={hero.url} alt={hero.title || property.societyBuildingName} fill priority sizes="(max-width: 1024px) 100vw, 65vw" className="object-cover" /><button onClick={() => setLightbox(media.indexOf(hero))} className="absolute right-3 bottom-3 flex min-h-11 items-center gap-2 border border-border bg-surface/95 px-3 text-[10px] font-bold uppercase"><Maximize2 className="h-3.5 w-3.5" />View photo</button></> : <div className="p-8 text-center"><Building2 className="mx-auto mb-4 h-16 w-16 text-gold" /><p className="text-xs font-bold uppercase tracking-wider">Your next property awaits</p></div>}</div>
        <div className="flex flex-col border-t border-border p-5 sm:p-8 lg:border-t-0 lg:border-l"><p className="mb-3 inline-flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.15em] text-muted-text"><span className="h-1.5 w-1.5 bg-gold" />{data.availabilityStatus.replaceAll('_', ' ')}</p><h1 className="text-3xl leading-tight font-black tracking-tight sm:text-4xl">{property.societyBuildingName}</h1><p className="mt-3 flex items-start gap-2 text-sm leading-relaxed text-muted-text"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-gold" />{property.locationArea}, {property.city}</p><div className="my-6 border-y border-border py-5"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-muted-text">{property.pricingType === 'RENT' ? 'Monthly rent' : 'Asking price'}</p><p className="mt-2 break-words text-3xl font-black tabular-nums text-gold sm:text-4xl">{price}</p></div><div className="grid grid-cols-3 gap-3">{[[BedDouble, property.bedrooms === null ? '—' : property.bedrooms === 0 ? 'Studio' : `${property.bedrooms} BHK`, 'Bedrooms'], [Bath, property.bathrooms ?? '—', 'Bathrooms'], [Maximize2, property.carpetAreaSqFt.toLocaleString('en-IN'), 'Carpet sq. ft.']].map(([Icon, value, label]) => { const Symbol = Icon as typeof BedDouble; return <div key={String(label)}><Symbol className="mb-2 h-5 w-5 text-gold" /><p className="text-sm font-bold">{String(value)}</p><p className="mt-1 text-[9px] uppercase tracking-wider text-muted-text">{String(label)}</p></div> })}</div><div className="mt-7 space-y-3"><a href={whatsapp} target="_blank" rel="noopener noreferrer" className={`${buttonClass} w-full bg-gold text-background`}>Arrange a viewing <ArrowUpRight className="h-4 w-4" /></a><a href={`tel:${company.phone.replace(/\s/g, '')}`} className={`${buttonClass} w-full`}><Phone className="h-3.5 w-3.5" />Talk to DreamKey</a></div></div>
      </div>
      <section className="mt-8 grid gap-6 lg:grid-cols-[1.65fr_1fr]"><div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black uppercase tracking-tight">Explore the property</h2><div className="flex gap-1">{(['ALL', 'PHOTOGRAPH', 'VIDEO'] as const).map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)} className={`min-h-10 px-3 text-[10px] font-bold uppercase ${filter === value ? 'bg-foreground text-background' : 'text-muted-text'}`}>{value === 'ALL' ? 'All media' : value === 'PHOTOGRAPH' ? 'Photos' : 'Videos'} ({media.filter(item => value === 'ALL' || item.category === value).length})</button>)}</div></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{gallery.map((item, index) => <article key={item.propertyMediaId} className="overflow-hidden border border-border bg-surface">{item.category === 'VIDEO' ? <div className="relative flex aspect-[4/3] items-center justify-center bg-surface-secondary"><video controls playsInline preload="none" className="h-full w-full object-contain" src={item.url} aria-label={item.title || `Property video ${index + 1}`} /></div> : <button onClick={() => setLightbox(media.indexOf(item))} className="relative block aspect-[4/3] w-full" aria-label={`Enlarge ${item.title || `property photo ${index + 1}`}`}><Image unoptimized src={item.url} alt={item.title || `Property photo ${index + 1}`} fill sizes="(max-width: 640px) 95vw, 400px" loading="lazy" className="object-cover transition-transform duration-300 hover:scale-[1.02]" /></button>}<p className="flex items-center gap-2 px-3 py-3 text-[10px] font-bold uppercase text-muted-text">{item.category === 'VIDEO' && <Film className="h-3.5 w-3.5 text-gold" />}{item.title || `${item.category === 'VIDEO' ? 'Video tour' : 'Property photo'} ${index + 1}`}</p></article>)}</div>{!gallery.length && <div className="border border-border p-8 text-center text-xs text-muted-text">No {filter === 'VIDEO' ? 'videos' : filter === 'PHOTOGRAPH' ? 'photos' : 'media'} selected for this listing.</div>}</div>
        <aside className="space-y-5"><section className="border border-border bg-surface p-5"><h2 className="mb-4 text-sm font-bold uppercase">Property at a glance</h2><dl className="divide-y divide-border text-xs">{[['Property type', property.propertyType], ['Listing', property.pricingType === 'RENT' ? 'For rent' : 'For sale'], ['Carpet area', `${property.carpetAreaSqFt.toLocaleString('en-IN')} sq. ft.`], ...(property.superBuiltUpAreaSqFt === null ? [] : [['Super built-up area', `${property.superBuiltUpAreaSqFt.toLocaleString('en-IN')} sq. ft.`]]), ...(property.floorNumber === null ? [] : [['Floor', `${property.floorNumber}${property.totalFloors === null ? '' : ` of ${property.totalFloors}`}`]]), ...(property.balconies === null ? [] : [['Balconies', String(property.balconies)]])].map(([label, value]) => <div key={label} className="flex justify-between gap-3 py-3"><dt className="text-muted-text">{label}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl></section>{property.amenities.length > 0 && <section className="border border-border bg-surface p-5"><h2 className="mb-4 text-sm font-bold uppercase">Amenities</h2><ul className="space-y-3">{property.amenities.map((amenity, index) => <li key={`${amenity}-${index}`} className="flex items-start gap-2 text-xs"><Check className="h-4 w-4 shrink-0 text-gold" />{amenity}</li>)}</ul></section>}<section className="border border-gold/30 bg-gold/5 p-5"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-gold">Personal assistance</p><h2 className="mt-3 text-lg font-black">Let’s find the right fit.</h2><p className="mt-2 text-xs leading-relaxed text-muted-text">Ask about availability, pricing, or a convenient time to see this property. Our team is here to help.</p><a href={`mailto:${company.email}?subject=${encodeURIComponent(`Enquiry: ${property.societyBuildingName}`)}`} className={`${buttonClass} mt-4 w-full`}><Mail className="h-3.5 w-3.5" />Email DreamKey</a></section></aside>
      </section>
    </main><DreamKeyPublicFooter company={company} />
    {lightbox !== null && <ClientModal title={media[lightbox].title || (media[lightbox].category === 'VIDEO' ? 'Property video' : 'Property photo')} onClose={() => setLightbox(null)} footer={<><button disabled={lightbox === 0} onClick={() => setLightbox(lightbox - 1)} className={buttonClass}><ChevronLeft className="h-4 w-4" />Previous</button><span className="flex items-center px-3 text-xs">{lightbox + 1} / {media.length}</span><button disabled={lightbox === media.length - 1} onClick={() => setLightbox(lightbox + 1)} className={buttonClass}>Next <ChevronRight className="h-4 w-4" /></button></>}><div className="relative flex h-[65dvh] items-center justify-center">{media[lightbox].category === 'VIDEO' ? <video key={media[lightbox].propertyMediaId} controls playsInline src={media[lightbox].url} className="max-h-full w-full" /> : <Image unoptimized src={media[lightbox].url} alt={media[lightbox].title || property.societyBuildingName} fill sizes="95vw" className="object-contain" />}</div></ClientModal>}
  </div>
}
