const fs=require('node:fs'),assert=require('node:assert/strict'),{createRequire}=require('node:module'),{randomUUID}=require('node:crypto')
const path=require('node:path')
const root=path.resolve(__dirname,'../..'), req=createRequire(root+'/package.json')
if (process.env.RUN_LIVE_API_TESTS !== '1') throw Error('Set RUN_LIVE_API_TESTS=1 to run against the configured development database.')
const env=req('dotenv').parse(fs.readFileSync(root+'/.dev.vars'))
const esbuild=createRequire(req.resolve('wrangler/package.json'))('esbuild')
const bundled=esbuild.buildSync({entryPoints:[root+'/src/index.ts'],bundle:true,platform:'node',format:'cjs',packages:'external',write:false}).outputFiles[0].text
const mod={exports:{}};new Function('require','module','exports',bundled)(req,mod,mod.exports);const app=mod.exports.default
const dbModule={exports:{}};new Function('require','module','exports',esbuild.transformSync(fs.readFileSync(root+'/src/db.ts','utf8'),{loader:'ts',format:'cjs'}).code)(req,dbModule,dbModule.exports)
const db=dbModule.exports.getPrisma(env.DATABASE_URL),token=randomUUID(),email=`codex-test-${randomUUID()}@example.invalid`
const ids={owners:[],brokers:[],properties:[],users:[]};let checks=0
async function call(method,path,body,status=200,auth=true){const response=await app.request('http://localhost/v1'+path,{method,headers:{...(auth?{Cookie:`auth_session=${token}`} : {}),'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})},env);const data=await response.json();assert.equal(response.status,status,`${method} ${path}: ${JSON.stringify(data)}`);checks++;return data}
async function main(){try{
const user=await db.user.create({data:{email,name:'Codex API Test',passwordHash:'unusable-test-account'}});ids.users.push(user.id)
await db.session.create({data:{userId:user.id,token,expiresAt:new Date(Date.now()+600000)}})
const inactive=await db.user.create({data:{email:email+'-inactive',name:'Inactive Test',passwordHash:'unusable',isActive:false}});ids.users.push(inactive.id)
await call('GET','/owners',undefined,401,false);await call('GET','/brokers',undefined,401,false);await call('POST','/properties/draft',{},401,false)
await call('POST','/owners',{name:'A',phone:'invalid'},400)
const badPartner=await call('POST','/owners',{name:'Test Owner',phone:'9876543210',primaryContactPartnerId:inactive.id},400);assert.equal(badPartner.details[0].field,'primaryContactPartnerId')
let owner=(await call('POST','/owners',{name:'Codex Test Owner',phone:'9876543210',notes:'Quiet home preferred',createdById:inactive.id},201)).owner;ids.owners.push(owner.id)
assert.equal(owner.createdById,user.id);assert.equal(owner.primaryContactPartnerId,user.id);assert.equal(owner.createdBy.id,user.id)
const unassigned=(await call('POST','/owners',{name:'Codex Unassigned Owner',phone:'9876543211',primaryContactPartnerId:null},201)).owner;ids.owners.push(unassigned.id);assert.equal(unassigned.primaryContactPartnerId,null)
owner=(await call('PUT',`/owners/${owner.id}`,{status:'INACTIVE',notes:'Updated preferences',createdById:inactive.id})).owner;assert.equal(owner.createdById,user.id)
owner=(await call('PUT',`/owners/${owner.id}`,{notes:'Partial update preserves status'})).owner;assert.equal(owner.status,'INACTIVE')
await call('PUT',`/owners/${owner.id}`,{status:'ACTIVE'})
assert((await call('GET','/owners?search=Codex%20Test%20Owner&status=ACTIVE')).owners.some(o=>o.id===owner.id))
assert((await call('GET','/owners/partners')).partners.some(p=>p.id===user.id))
await call('GET','/owners/stats');await call('GET','/owners?limit=500',undefined,400);await call('GET','/owners/not-a-uuid',undefined,400)
await call('GET',`/owners/${randomUUID()}`,undefined,404)
let broker=(await call('POST','/brokers',{name:'Codex Test Broker',phone:'9876543212',maxDealValue:99999},201)).broker;ids.brokers.push(broker.id);assert.equal(broker.primaryContactPartnerId,user.id);assert(!('maxDealValue' in broker))
await call('PUT',`/brokers/${broker.id}`,{primaryContactPartnerId:inactive.id},400)
await call('PUT',`/brokers/${broker.id}`,{notes:'Test updated',primaryContactPartnerId:null})
await call('PUT',`/brokers/${broker.id}`,{status:'INACTIVE',societyExpertise:['Test Society']})
broker=(await call('PUT',`/brokers/${broker.id}`,{notes:'Partial update keeps expertise'})).broker;assert.equal(broker.status,'INACTIVE');assert.deepEqual(broker.societyExpertise,['Test Society'])
await call('PUT',`/brokers/${broker.id}`,{status:'ACTIVE'})
await call('GET','/brokers/stats');await call('GET','/brokers?sortBy=maxDealValue',undefined,400)
const listing={propertyType:'FLAT',pricingType:'SALE',societyBuildingName:'Codex API Test Listing',locationArea:'Test Area',pincode:'400001',city:'Mumbai',carpetAreaSqFt:500,askingPrice:1000000,accessType:'DIRECT',ownerId:owner.id}
await call('POST','/properties',{...listing,ownerId:null},400)
await call('POST','/properties',{...listing,brokerId:broker.id},400)
let property=(await call('POST','/properties',listing,201)).property;ids.properties.push(property.id);assert.equal(property.owner.id,owner.id);assert.equal(property.sourcePartnerId,user.id)
assert((await call('GET',`/owners/${owner.id}/properties`)).properties.some(p=>p.id===property.id))
assert.equal((await call('GET',`/owners/${owner.id}`)).owner._count.properties,1)
assert((await call('GET',`/properties?ownerId=${owner.id}`)).properties.some(p=>p.id===property.id))
property=(await call('PUT',`/properties/${property.id}`,{accessType:'BROKER',brokerId:broker.id})).property;assert.equal(property.ownerId,null);assert.equal(property.brokerId,broker.id)
assert.equal((await call('GET',`/owners/${owner.id}/properties`)).pagination.total,0)
assert.equal((await call('GET',`/brokers/${broker.id}/properties`)).pagination.total,1)
property=(await call('PUT',`/properties/${property.id}`,{notes:'Only change notes'})).property;assert.equal(property.accessType,'BROKER');assert.equal(property.brokerId,broker.id)
await call('PUT',`/properties/${property.id}`,{ownerId:owner.id},400)
await call('PUT',`/properties/${property.id}`,{accessType:'DIRECT'},400)
property=(await call('PUT',`/properties/${property.id}`,{accessType:'DIRECT',ownerId:owner.id})).property;assert.equal(property.brokerId,null)
const draft=(await call('POST','/properties/draft',{} ,201)).property;ids.properties.push(draft.id)
await call('PUT',`/properties/${draft.id}`,{...listing,isDraft:false});assert.equal((await call('GET',`/owners/${owner.id}/properties`)).pagination.total,2)
await call('PATCH',`/properties/${property.id}/status`,{availabilityStatus:'UNDER_NEGOTIATION'})
await call('DELETE',`/owners/${owner.id}`);assert.equal((await call('GET',`/properties/${property.id}`)).property.ownerId,null)
await call('DELETE',`/brokers/${broker.id}`)
await call('DELETE',`/properties/${draft.id}`);await call('DELETE',`/properties/${property.id}`)
console.log(`Live authenticated API checks passed: ${checks}. Creator attribution, validation, CRUD, draft publication, automatic link changes, and deletion preservation verified.`)
}finally{
await db.property.deleteMany({where:{id:{in:ids.properties}}});await db.owner.deleteMany({where:{id:{in:ids.owners}}});await db.broker.deleteMany({where:{id:{in:ids.brokers}}});await db.propertyAuditLog.deleteMany({where:{userId:{in:ids.users}}});await db.user.deleteMany({where:{id:{in:ids.users}}});await db.$disconnect();console.log('Disposable API test records cleaned up.')
}}
main().catch(error=>{console.error(error.message);process.exitCode=1})
